# Generated by Django 5.0 on 2026-04-10 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('electronics', 'Electronics'), ('clothing', 'Clothing'), ('home', 'Home & Kitchen'), ('books', 'Books'), ('toys', 'Toys & Games')], default='electronics', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
